project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

#bibliography: files/bib/references.bib
csl: files/bib/apa.csl

website:
  title: "Cursos de Cesar Cornejo"
  site-url: "https://cornejo-cursos.github.io/writing-papers/"
  page-navigation: true
  favicon: "/files/img/pucp-favicon-512.png"

  navbar: 
    pinned: true
    background: primary
    foreground: light
    right:
      - text: "Sílabo"
        file: ensayo/index.qmd
        icon: book-half
      - text: "Contenido"
        file: caso/index.qmd
        icon: book-half
      - text: "Ejemplos"
        href: ej/tipo.qmd
        icon: binoculars
      - text: "Recursos"
        file: resource/index.qmd
        icon: bookshelf

  sidebar:

    - title: "Sílabo"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Sumilla"
          file: silabo/index.qmd
          icon: map

    - title: "Contenido"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Propuesta"
          file: caso/index.qmd
          icon: map

    - title: "Ejemplos"
      contents:
            - ej/tipo.qmd
            - ej/especialidad.qmd

    - title: "Recursos"
      contents:
            - resource/index.qmd
            - resource/rubrica.qmd
            - reglamentos/index.qmd


  page-footer:
    left: |
      Contenido <i class="bi bi-cc-circle"></i> {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
  pdf:
    documentclass: scrreprt
