project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

#bibliography: files/bib/references.bib
csl: files/bib/apa.csl

website:
  title: "Cursos de Cesar Cornejo"
  site-url: "https://cornejo-cursos.github.io/writing-papers/"
  page-navigation: true
  favicon: "/files/img/pucp-favicon-512.png"

  navbar: 
    pinned: true
    background: primary
    foreground: light
    right:
      - text: "Ejemplos de tesis"
        href: ej/tipo.qmd
        icon: list-check
      - text: "Estudio de caso 1"
        file: ej/arrunategui2020.qmd
        icon: binoculars
      - text: "Estudio de caso 2"
        href: ej/otero2022.qmd
        icon: binoculars
        
  page-footer:
    left: |
      Contenido <i class="bi bi-cc-circle"></i> {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
  pdf:
    documentclass: scrreprt
