---
title: "Estructura"
bibliography: references.bib
reference-location: margin

number-sections: true
number-depth: 2
crossref:
  chapters: true

engine: knitr
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: justify
La estructura de una tesis cumple un papel crucial al sostener, organizar y dar forma al argumento, permitiendo que las ideas se desarrollen de manera clara y efectiva. En esta guía, me propongo ofrecerte un marco estructural sólido, independientemente de las diversas posturas ontológicas, epistemológicas y enfoques metodológicos presentes en nuestras disciplinas.

En este capítulo, te presento los componentes esenciales que debes incorporar en el cuerpo principal de tu tesis, destacando el propósito que cada uno cumple en el contexto del trabajo académico. Estos componentes son fundamentales para cualquier tesis rigurosa; sin embargo, la disposición, agrupación y nombres de los capítulos de la tesis son flexibles. Este enfoque modular te ofrece múltiples opciones para estructurar tu investigación, permitiéndote ajustarla según las particularidades específicas de tu enfoque y disciplina.

A lo largo de este capítulo, cumpliré tres objetivos. Primero, te explicaré lo que son los componentes, las razones de su uso y su relación con los capítulos (ver @fig-componentes). En segundo lugar, te presentaré todos los componentes en un orden lógico. Por último, a lo largo del capítulo exploraré algunas elecciones de agrupación de estos componentes e indicaré los capítulos de tesis sobresalientes dónde encontrar los ejemplos más relevantes. Algunos ejemplos corresponden a *ejemplos analizados*, es decir, a tesis completas que he analizado en un capítulo independiente de esta guía. Otros ejemplos corresponden a tesis no analizadas en esta guía, pero disponibles a texto completo. En todos los casos, he seleccionado como ejemplos los capítulos o los componentes específicos de tesis sobresalientes.
:::

# Componentes agrupados en capítulos {.unnumbered}

Mi propuesta para pensar la estructura está basada en **componentes** que se agrupan en **capítulos** en el manuscrito final de la tesis.

::: callout-tip
## Ideas centrales

-   Los **componentes** se refieren a las secciones principales que estructuran y organizan el contenido del trabajo académico.
-   Cada componente cumple propósitos específicos dentro de la estructura de la tesis.
-   La tesis que debes escribir se organiza en **capítulos**. Cada capítulo tiene uno o más **componentes**.
:::

::: {#fig-componentes}
```{mermaid}
flowchart LR
  C1(Componente 1) --> A[Capítulo 1]
  C2(Componente 2) --> B[Capítulo 2]
  C3(Componente 3) --> C[Capítulo 3]
  C4(Componente 4) --> D[Capítulo 4]
  C5(Componente 5) --> D
  C6(Componente 6) --> D
  C7(Componente 7) --> E[Capítulo 5]
  C8(Componente 8) --> F[Capítulo 6]
  C9(Componente 9) --> F
  C10(Componente 10) --> G[Capítulo 7]
  C11(Componente 11) --> G

```

Relación entre componentes y capítulos de la tesis
:::

## Definición {.unnumbered}

::: justify
En el contexto de una tesis, los **componentes** se refieren a las secciones principales que estructuran y organizan el contenido del trabajo académico. Cada componente aborda un aspecto específico del proceso de investigación y contribuye a la comprensión integral del tema estudiado. Estos componentes tienen diferentes denominaciones en diferentes disciplinas y tradiciones de investigación, que prefieren hablar de secciones, partes o capítulos. Además, el término **componente** no es usado en las guías de investigación o textos de metodología. Sin embargo, en todos los trabajos académicos rigurosos se pueden identificar una parte del texto que cumple los propósitos de estos **componentes**. El orden en que presento los **componentes** es el más intuitivo: guía al lector a través de la narrativa académica, desde el planteamiento del problema hasta las conclusiones y sugerencias para futuras investigaciones. Sin embargo, el orden y la agrupación de los diferentes componentes son aspectos flexibles con los cuales el investigador puede maniobrar. Lo importante es seguir un orden lógico que facilite la comprensión del lector y la presentación ordenada del trabajo de investigación.

El trabajo final (la tesis o manuscrito) no está dividido en **componentes**, está dividido en capítulos. Los capítulos tienen uno o más componentes. A continuación, te presento las ventajas de pensar y organizar tu trabajo en base a **componentes**:
:::

## Razones {.unnumbered}

::: justify
1.  **Claridad estructural:** El término "componentes" sugiere una estructura modular y clara. Cada componente cumple un papel definido en la construcción global de la tesis, facilitando la comprensión del lector sobre cómo se desarrolla la investigación.

2.  **Flexibilidad y adaptabilidad:** Trabajar con "componentes" proporciona flexibilidad para adaptarse a diferentes enfoques y estilos de escritura. A diferencia de términos más rígidos como **capítulos** o **secciones**, **componentes** permite una adaptación más fluida a la naturaleza específica de cada investigación.

3.  **Énfasis en la interconexión:** Al referirse a las partes de la tesis como "componentes", se resalta la interconexión y la interdependencia entre ellos. Esto enfatiza que cada elemento contribuye de manera integral al conjunto, reflejando la coherencia y cohesión del trabajo académico.

4.  **Concordancia con un enfoque modular:** El uso del término "componentes" se alinea con un enfoque modular en la escritura académica. Cada componente puede considerarse como una unidad autónoma, pero al mismo tiempo, se conecta y relaciona con los demás para formar una estructura integral.

5.  **Facilita la guía y referencia:** Al hablar de "componentes", se hace más sencillo para el autor y el lector referirse a secciones específicas de la tesis. Este enfoque facilita la guía, la revisión y la referencia cruzada entre diferentes partes del trabajo.

En resumen, el término **componentes** se elige por su capacidad para comunicar de manera clara y flexible la estructura y organización de una tesis, fomentando la comprensión y facilitando la navegación a lo largo del trabajo académico.
:::

# Orden lógico {.unnumbered}

::: justify
El orden que te presento a continuación es referencial, y tu puedes cambiarlo. Sin embargo, esta propuesta sigue un orden lógico que guía al lector a través de un proceso coherente de investigación. Comienza con el "Planteamiento del problema de investigación", establece el contexto y la necesidad de la investigación. Luego, la sección "Estado del arte" realiza una revisión de la literatura existente, identifica brechas y delinea los límites del conocimiento actual sobre un tema bien delimitado dentro de una disciplina muy específica.

Después, el "Marco teórico", profundiza en la revisión de literatura, define conceptos clave y relaciona teorías existentes con las preguntas de investigación. La transición hacia "Contexto" se centra en proporcionar antecedentes y analizar el entorno actual, conectando teorías con la realidad. "Metodología y diseño del estudio" guía al lector a través de las decisiones metodológicas, y "Detalles del caso" aterriza los aspectos conceptuales del diseño en el caso específico que estudia este trabajo.

Las secciones restantes, desde "Presentación de Datos" hasta "Conclusiones", siguen el flujo lógico de análisis, discusión e interpretación. "Implicaciones y Relevancia" conecta los resultados con la aplicación práctica y teórica, mientras que "Conclusiones" cierra la tesis resumiendo hallazgos clave y reflexionando sobre la contribución única, proporcionando un cierre lógico y sugiriendo futuras direcciones. Este orden permite una presentación cohesiva y comprensible del trabajo de investigación.
:::

# Planteamiento del problema de investigación

::: callout-tip
## Propósito

-   **Definir la problemática:**
    -   Definir claramente el problema de investigación que la tesis abordará
-   **Formular preguntas específicas:**
    -   Formular preguntas de investigación específicas y objetivos claros
-   **Establecer relevancia:**
    -   Establecer la importancia y relevancia del problema en el contexto de la disciplina
-   **Plantear justificación:**
    -   Presentar una justificación convincente para abordar el problema propuesto
:::

::: justify
@arrunategui2020 y @anaya2020 emplean el primer capítulo para desarrollar este componente. [Ver el ejemplo analizado del planteamiento del problema que realiza Arrunátegui](/ej/arrunategui2020.html#sec-problema).
:::

# Estado del arte

::: callout-tip
## Propósito

-   **Revisión de la literatura:**
    -   Realizar una revisión exhaustiva de los avances y conocimientos existentes, en el área de estudio elegido, con respecto al problema de investigación planteado
-   **Identificar controversias actuales:**
    -   Identificar acuerdos y desacuerdos con respecto al problema de investigación planteado
-   **Identificar limitaciones:**
    -   Identificar limitaciones ---metodológicas, empíricas o teóricas--- de la investigación disponible
-   **Identificar vacíos:**
    -   Identificar vacíos en la investigación actual y áreas donde se necesita más estudio
:::

En algunos casos, este componente tiene un capítulo propio. Por ejemplo, el capítulo 3 de @anaya2020 (Estado del arte) revisa teoría e identifica 2 brechas: "Una primera entre la teoría sobre desastres (desde las CC.SS) y las estrategias de gestión de desastre; la segunda, parte a la vez de las políticas propuestas y las iniciativas locales de GRD" (p. 5). En otros casos, este componente puede integrarse en otro capítulo con un objetivo más general. Por ejemplo, @otero2022 desarrolla este componente como la tercera parte de su segundo capítulo (Marco teórico) y la denomina Estudios previos. [Ver ejemplo](/ej/otero2022.html#capítulo-2.-marco-teórico).

# Marco teórico

::: callout-tip
## Propósito

-   **Profundizar en literatura:**
    -   Profundizar en la revisión de literatura para establecer una base sólida.
-   **Definir conceptos clave:**
    -   Definir y conceptualizar los términos clave que se utilizarán en la interpretación.
-   **Relacionar teorías:**
    -   Relacionar las teorías existentes con las preguntas de investigación específicas.
-   **Desarrollar expectativas teóricas:**
    -   Desarrollar expectativas teóricas sólidas para guiar el análisis.
:::

::: justify
En la mayoría de los casos, el marco teórico se presenta como un capítulo de fácil identificación y una estructura simple que organiza la teoría en conglomerados de literatura fácilmente identificables. Por ejemplo, el marco teórico de un estudio sobre la evolución de las políticas educativas propuestas por un determinado partido político puede organizarse en: teorías de la equidad educativa, la teoría del capital humano y las perspectivas sociológicas sobre la educación. En otros casos, el objeto de estudio está más imbricado con la teoría (ver el ejemplo analizado del capítulo 2 de @otero2022. Además, en otros casos, el marco teórico se puede presentar de manera más orgánica con otros componentes que ayudan a establecer una base sólida para el estudio: ver el capítulo 2 de @sanchez2023 llamado *Marcos Referenciales*. Además, la teoría entra en diálogo transparente y sintético en una herramienta usual en las investigaciones: una tabla de operacionalización de variables. [Ver el Anexo 1 de Arrunátegui (2020) ](/ej/arrunategui2020.html#tabla-de-operacionalización) para ver una tabla de operacionalización de variables.
:::

# Contexto

::: callout-tip
## Propósito

-   **Proporcionar antecedentes:**
    -   Ofrecer antecedentes y contexto histórico relacionados con el problema de investigación.
-   **Analizar contexto actual:**
    -   Analizar el contexto actual en el que se desarrolla el fenómeno de estudio.
-   **Identificar actores clave:**
    -   Identificar y describir a los actores clave y las dinámicas sociales relevantes.
-   **Conectar con teoría:**
    -   Conectar el contexto con teorías existentes que puedan guiar el estudio.
:::

::: justify
Esta sección puede abordar aspectos históricos, sociales, políticos y culturales que contextualizan el problema de investigación. Su objetivo central es proporcionar al lector una visión general del entorno más amplio en el que se encuentra el problema de investigación.

Ver el capítulo 4 de @aleman2023 (El contexto del debate) para explorar la presentación del contexto en una investigación que busca identificar las estrategias de un actor con respecto a un proyecto de ley. Ver el capítulo 3 de @sanchez2023 para explorar la presentación del contexto de una tesis busca reconstruir un periodo más extenso (la historia del campo de la ficción en el Perú del siglo XIX y XX).

En algunos casos, contextualizar un problema de investigación requiere de una revisión de las reflexiones teóricas relevantes. En estos casos, esta sección identifica las teorías y los conceptos más apropiados. Sin embargo, en la mnayoría de los casos se requiere una sección teórica (marco teórico) de revisión detallada y crítica de teorías relevantes que informarán directamente el marco conceptual de la investigación. Ambos componentes (Contexto y Marco teórico) trabajan juntos para establecer una sólida base teórica y contextual para el estudio.
:::

# Metodología y diseño del estudio

::: callout-tip
## Propósito

-   **Describir metodología:**
    -   Describir exhaustivamente la metodología de investigación utilizada.
-   **Justificar elecciones:**
    -   Justificar la elección del enfoque de estudio de caso y otros métodos empleados.
-   **Detallar proceso de selección:**
    -   Detallar el proceso de selección del caso y explicar las razones detrás de esta elección.
-   **Especificar métodos:**
    -   Especificar los métodos de recopilación y análisis de datos.
:::

::: justify
En algunas disciplinas, se requiere un análisis detallado de la elección metodológica. Ver @arrunategui2020 quien recurre a diversos autores para justificar diferentes aspectos metodológicos de su investigación. En algunas disciplinas, la elección de una enfoque o herramienta determinada se considera suficiente para este producto académico específico (una tesis de licenciatura). Ver @otero2022 para una tesis que solo presenta su elección metodológica principal (metodología cualitativa, *process tracing*) en su introducción. Ver el capítulo 5 de @anaya2020 para una discusión detallada del diseño de su investigación.
:::

# Detalles del caso

::: callout-tip
## Propósito

-   **Presentar ubicación:**
    -   Presentar la ubicación geográfica y temporal del caso de manera detallada.
-   **Analizar entorno social:**
    -   Analizar el entorno social, político y cultural relevante.
-   **Describir actores principales:**
    -   Identificar y describir a los actores principales involucrados en el caso.
-   **Explorar relaciones sociales:**
    -   Explorar las relaciones y dinámicas sociales clave en el contexto del caso.
:::

::: justify
Ver el la tabla 5, capítulo 5 de @anaya2020 como un ejemplo de presentación de los criterios de selección del caso de estudio. [Ver el ejemplo analizado de la presentación del caso que realiza @arrunategui2020](/ej/arrunategui2020.html#los-casos).
:::

# Presentación de datos

::: callout-tip
## Propósito

-   **Exponer datos claramente:**
    -   Exponer los datos recopilados de manera clara y organizada.
-   **Utilizar narrativas:**
    -   Utilizar narrativas, citas y ejemplos para ilustrar hallazgos.
-   **Integrar elementos visuales:**
    -   Integrar elementos visuales como mapas, gráficos y fotografías para enriquecer la presentación.
:::

::: justify
El uso de los datos recabados durante la investigación es muy variado. En algunos casos, estos se presentan en una capítulo independiente. @otero2022 reconstruye su caso de estudio en el capítulo 4, porque el enfoque del *process tracing* así lo demanda. [Ver este ejemplo analizado.](/ej/otero2022.html#capítulo-4.-reconstrucción-del-caso) En otros casos, la presentación de los datos se integra con el análisis y no es posible distinguirlas (ver el ejemplo analizado del capítulo 4 de @arrunategui2020. En ambos casos, la clave está en asegurarse de que el lector pueda seguir lógicamente la narrativa del estudio y comprender la relación entre los datos presentados y las interpretaciones desarrolladas.
:::

# Análisis

::: callout-tip
## Propósito

-   **Interpretar datos:**
    -   Interpretar los datos a la luz del marco teórico establecido.
-   **Relacionar con teorías:**
    -   Relacionar los hallazgos con las teorías existentes y proponer nuevas interpretaciones.
-   **Identificar patrones y excepciones:**
    -   Identificar patrones, conexiones y excepciones significativas en los datos.
-   **Evaluar validez y sesgos:**
    -   Evaluar críticamente la validez de los resultados y discutir posibles sesgos.
:::

::: justify
Esta sección busca comprender significados más allá de los datos brutos presentados. Como indicamos en la sección anterior, se puede optar por presentar ambos componentes (presentación de datos y su análisis) de manera integrada en uno o más capítulos. Además, es posible distinguir los propósitos del análisis de los propósitos de la discusión.

Ver el ejemplo analizado del [capítulo 4 de @arrunategui2020](/ej/arrunategui2020.html#capítulo-4.-análisis) y el ejemplo analizado del [capítulo 5 de @otero2022](/ej/arrunategui2020.html#capítulo-4.-análisis) que constituyen dos ejemplos destacados de análisis en tesis sobresalientes de la facultad.
:::

# Discusión

::: callout-tip
## Propósito

-   **Contextualizar resultados:**
    -   Contextualizar los resultados dentro del cuerpo de conocimientos existente.
-   **Comparar con investigaciones previas:**
    -   Comparar los resultados con estudios previos y destacar similitudes y diferencias.
-   **Reflexionar críticamente:**
    -   Reflexionar críticamente sobre la calidad y confiabilidad de los resultados.
-   **Generar preguntas futuras:**
    -   Generar nuevas preguntas de investigación basadas en los resultados obtenidos.
-   **Considerar limitaciones:**
    -   Considerar y discutir las limitaciones del estudio.
:::

Este componente se puede integrar con otros en los capítulos finales de la tesis. Algunos autores deciden integrarla en la sección final que a veces se denomina conclusiones. En cualquier caso, es importante tener en cuenta los propósitos específicos de una discusión, incluso si el trabajo tiene un capítulo individual dedicado a desarrollar este componente.

# Implicaciones y relevancia

::: callout-tip
## Propósito

-   **Relacionar con contexto práctico y teórico:**
    -   Relacionar los resultados con el contexto práctico y teórico de la disciplina (implicaciones).
-   **Destacar significado práctico:**
    -   Destacar la relevancia y el significado práctico de los hallazgos.
-   **Considerar impacto en políticas:**
    -   Considerar cómo los resultados pueden influir en políticas, acciones o toma de decisiones.
-   **Contribuir al conocimiento:**
    -   Contribuir al entendimiento teórico o práctico del fenómeno estudiado.
:::

Al igual que el componente anterior, este componente se puede integrar con otros en los capítulos finales de la tesis. Algunos autores deciden integrarla en la sección final que a veces se denomina conclusiones. En cualquier caso, es importante tener en cuenta los propósitos específicos de una discusión, incluso si el trabajo tiene un capítulo individual dedicado a desarrollar este componente.

# Conclusiones

::: callout-tip
## Propósito

-   **Resumir hallazgos clave:**
    -   Resumir de manera concisa los hallazgos clave del estudio.
-   **Reflexionar sobre limitaciones:**
    -   Reflexionar sobre las limitaciones del estudio y posibles áreas de mejora.
-   **Destacar contribución única:**
    -   Destacar la contribución única de la tesis al campo de estudio.
-   **Generar cierre lógico:**
    -   Proporcionar un cierre lógico a la narrativa general del trabajo.
-   **Sugerir direcciones futuras:**
    -   Sugerir posibles direcciones para investigaciones futuras basadas en los resultados obtenidos.
:::

Como se anticipó en los dos componentes anteriores, un capítulo final denominado conclusiones en ocasiones desarrolla los propósitos correspondientes a varios componentes (discusión, implicaciones y relevancia, conclusiones). En ocasiones, este capítulo recibe otra denominación que expresa mejor los énfasis y preferencias de la investigadora, por ejemplo, [ver el capítulo 5 de @arrunategui2020 denominado Reflexiones finales y recomendaciones](/ej/arrunategui2020.html#capítulo-5.-reflexiones-finales-y-recomendaciones).

Además, [ver el capítulo 6 de @otero2022](/ej/otero2022.html#capítulo-6.-conclusiones) denominado *Conclusiones*.

# Referencias {.unnumbered}

::: callout-tip
## Objetivo

-   Incluir todas las fuentes citadas en el estudio de caso en estilo de citado APA.
:::

# Anexos {.unnumbered}

::: callout-tip
## Objetivo

-   Incluir material adicional relevante, como entrevistas completas, documentos originales o datos suplementarios.
-   Explicar la pertinencia de cada anexo para la comprensión global del estudio.
:::
