---
title: "2 Rigurosidad"

bibliography: references.bib
reference-location: margin

number-sections: true
number-depth: 2
crossref:
  chapters: true

engine: knitr
---

# La rigurosidad en el estudio de caso

## Rigurosidad del manuscrito (tesis escrita completa)

Estructura lógica rigurosa, evidencia convincente del caso y conexiones con la literatura académica pertinente.

1.  La estructura lógica rigurosa nos permite evaluar si su postura es razonable y defendible. Una postura razonable está justificada por sus argumentos. Una postura defendible se puede defender de refutaciones. Además, cada argumento requiere evidencia como respaldo. La lógica nos permite evaluar si la evidencia respalda el argumento que usted está presentando e identificar los puntos débiles para refutar.

2.  La evidencia analizada es convincente para una audiencia de científicos sociales bien delimitada (la sociología política)

3.  Por último, una argumentación académica rigurosa demuestra un dominio de la literatura pertinente.

## Rigurosidad del diseño

Problema de investigación → pregunta de investigación → conceptos y marcos teóricos → diseño de investigación → recolección de datos → análisis de datos

# Justificar las elecciones

En esta guía recomiendo escribir con el objetivo de persuadir al lector de la pertinencia todas nuestras elecciones (metodológicas, analíticas y de escritura). Ello demanda del escritor lo siguiente: 1) hacer explícitas todas las elecciones y 2) justificar dichas elecciones.

## Elecciones metodológicas

Frente a la diversidad de posturas ontológicas, epistemológicas, tradiciones y enfoques que conviven en nuestras disciplinas, es común declararse pluralista y es fácil resbalar en el eclecticismo, donde se relajan los criterios para evaluar el rigor que cada enfoque ha desarrollado. En esta guía, doy un paso atrás y propongo el agnosticismo en lugar del pluralismo metodológico. La diferencia la entiendo de la siguiente manera: cualquier investigación deberá demostrar su rigurosidad mediante la justificación minuciosa de sus elecciones metodológicas. Esto no es siempre posible en un artículo publicado por que existen restricciones de espacio severas y la audiencia de lectores es más especializada. Una audiencia especializada no necesita leer una enésima justificación de una ruta metodológica. Una tesis, por el contrario, tiene más espacio y evalúa de manera explícita las justificaciones metodológicas de sus discentes. Esta guía asume y recomienda escribir para el lector incrédulo, no para el investigador pluralista que acepta a priori que muchos diseños poseen el mismo valor, sino para el evaluador descreído que requiere persuasión.

## Elecciones analíticas

## Elecciones de escritura
