---
title: Testing Callouts
---


::: {.border}
This content can be styled with a border
:::

::::: {#special .sidebar}

::: {.warning}
Here is a warning.
:::

More content.
:::::

[This is *some text*]{.class key="val"}

[This is good]{#id .class key1="val1" key2="val2"}

## HEAD
Este libro ofrece:

:::{.callout-tip}
Ideas principales: 
`ideas clave`, `la esencia`, `tips` y `secretos del arte`
:::

:::{.callout-note}
Información adicional más relevante:
`normas`, `recursos`, `herramientas`, `estadísticas` y `tendencias`
:::

:::{.callout-warning}
Ejemplos: 
`trabajos sobresalientes`
:::

:::{.callout-important}
Principales recursos para conocer más:
`lecturas clave` y `fuentes más relevantes`
:::

:::{.callout-caution}
Advertencias: 
`errores frecuentes`, `faltas graves`, `peligros` y `descuidos comunes`
:::




`texto dentro de símbolo de código` 
=======
:::{.callout-note}
Note that there are five types of callouts, including: 
`note`, `tip`, `warning`, `caution`, and `important`.
:::

:::{.callout-tip}
Note that there are five types of callouts, including: 
`note`, `tip`, `warning`, `caution`, and `important`.
:::

:::{.callout-important}
Note that there are five types of callouts, including: 
`note`, `tip`, `warning`, `caution`, and `important`.
:::

`texto dentro de símbolo de código`
>>>>>>> 15370f8c3dd33e559ff47b7c864d1f979c55f170



-   <i class="bi bi-twitter"></i>   [{{< var instructor.twitter >}}](https://www.twitter.com/%7B%7B%3C%20var%20instructor.twitter%20%3E%7D%7D)
-   <i class="bi bi-linkedin"></i>   [{{< var instructor.linkedin >}}](https://www.linkedin.com/in/%7B%7B%3C%20var%20instructor.linkedin%20%3E%7D%7D)
