---
title: "Escribir un estudio de caso"
subtitle: "Guía de escritura de tesis tipo estudio de caso no comparativo"
date-format: DD/MM/YYYY
date: "12/06/2023"

bibliography: references.bib
reference-location: margin

number-sections: true
number-depth: 2
crossref:
  chapters: true

engine: knitr
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

# Estructura, ejemplos, calificación {.unnumbered}
::: justify
Esta guía te suministra tres insumos indispensables para escribir una tesis sobresaliente: una estructura lógica para escribir tu trabajo, ejemplos analizados de tesis bien escritas y los criterios de calificación que se emplean para evaluar una tesis sobresaliente.

La estructura contiene todos los componentes que necesitas desarrollar cuando escribes una tesis. Los ejemplos te ofrecen análisis de algunas de las mejores tesis recientes sustentadas en la facultad.  Los criterios de calificación desagregan la rúbrica oficial de calificación de tesis de la facultad y los emplean para calificar una tesis sobresaliente.
:::

# Estructura

::: callout-tip
## Idea central

Este capítulo discute todos los componentes textuales ---secciones con propósitos específicos--- que necesitas desarrollar para escribir una tesis de este tipo.
:::

::: justify
La estructura de una tesis cumple un papel crucial al sostener, organizar y dar forma al argumento, permitiendo que las ideas se desarrollen de manera clara y efectiva. En esta guía, te presento un marco estructural sólido pero flexible, independientemente de las diversas posturas ontológicas, epistemológicas y enfoques metodológicos presentes en nuestras disciplinas.

[En este capítulo](/caso/02-caso.qmd), te presento los componentes esenciales que debes incorporar en el cuerpo principal de tu tesis, destacando el propósito que cada uno cumple en el contexto del trabajo académico. A lo largo de este capítulo, cumpliré tres objetivos. Primero, te explicaré lo que son los componentes, las razones de su uso y su relación con los capítulos. En segundo lugar, te presentaré todos los componentes en un orden lógico. Por último, a lo largo del capítulo exploraré algunas elecciones de agrupación de estos componentes e indicaré los capítulos de tesis sobresalientes dónde encontrar los ejemplos más relevantes.
:::

# Ejemplos

::: callout-tip
## Idea central

Esta Guía proporciona 2 tipos de ejemplos, ejemplos analizados y ejemplos de estructuras. Ambos tipos de ejemplos corresponden a trabajos recientes que puedes usar como inspiración y modelo para escribir tu tesis.
:::

## Ejemplos analizados
::: justify
Esta Guía ilustra sus indicaciones con ejemplos de tesis recientes de la facultad de Ciencias Sociales de la PUCP que obtuvieron la mención (calificación) de sobresaliente. El capítulo [Arrunátegui 2020](/ej/arrunategui2020.qmd) analiza una tesis sobresaliente que emplea un enfoque etnográfico, realiza entrevistas, observación ---participante y no participante--- y revisa documentos para analizar un problema de investigación. El capítulo [Otero 2022](/ej/otero2022.qmd) analiza una tesis que realiza un *process tracing* para reconstruir y explicar la reglamentación de una ley.   
:::

## Ejemplos de estructuras

::: justify
[Este capítulo](/caso/02-caso.qmd) esquematiza la estructura de un número mayor de tesis sobresalientes. En estos casos, no se analiza cada componente de la tesis, solo se presenta la pregunta de investigación y la estructura en el lenguaje empleado por esta Guía. Por lo general, los autores no eligen nombres genéricos para titular sus capítulos. Además, en el [Repositorio de tesis](https://repositorio.pucp.edu.pe/index/handle/123456789/9120), no existe información pública sobre la calificación que obtuvo cada trabajo. Por ello, esta sección esquematiza las estructuras de varias tesis sobresalientes, lo que te permite indagar más en ellos o simplemente reconocer las varias estructuras que los autores eligen para organizar sus trabajos. Por último, los ejemplos agrupados en este capítulo se emplean en otros capítulos de la Guía para dirigirte hacia ejemplos relevantes.
:::

## Listado de ejemplos

::: justify
Además, en la sección [Ejemplos](/ej/tipo.qmd) se listan y clasifican las tesis sobresalientes empleadas en esta Guía.
:::

# Calificación

::: callout-tip
## Idea central

Los criterios de calificación desagregan la rúbrica oficial de calificación de tesis de la facultad y los emplean para calificar una tesis sobresaliente.
:::

::: justify
[Este capítulo](/caso/03-caso.qmd) presenta los criterios de evaluación de la tesis en la facultad de Ciencias Sociales de la PUCP. Además, discute el significado de estos criterios en el caso de una tesis de este tipo y, por último, ilustra con ejemplos cómo se logra cumplir con el máximo nivel de desempeño en cada criterio (sobresaliente).
:::

## ¿Cómo citar esta guía?

Pendiente: Generar DOI para esta guía.

Cornejo, Cesar 2023. Guía de escritura de tesis tipo estudio de caso.

<p class="buttons" style="text-align:center;">

[<i class="bi bi-list-check"></i> Leer esta guía en orden](/caso/01-caso.qmd){.btn .btn-danger} [<i class="bi bi-arrow-up-right-square"></i> Ver ejemplos de este tipo de tesis](/ej/tipo.qmd){.btn .btn-danger}

</p>

