---
title: "¿Qué ofrece esta guía?"
---

## Ejemplos, estándares, estructuras

Esta guía ofrece ejemplos, estándares y estructuras textuales (formatos). Los ejemplos te ofrecen modelos e inspiración seleccionados de entre las mejores tesis recientes de la facultad. Los estándares de calidad te ofrecen explicaciones sobre los criterios de calificación. Las estructuras textuales te orientan en la escritura de todas las secciones de una tesis de estudio de caso.

### Para encontrar ejemplos, modelos e inspiración

::: callout-tip
## Ejemplos

Esta Guía te dirige hacia una selección de trabajos recientes que puedes usar como inspiración y modelo para escribir tu tesis.
:::

Esta Guía ilustra sus indicaciones con ejemplos de tesis recientes de la facultad de Ciencias Sociales de la PUCP que obtuvieron la mención (calificación) de sobresaliente. En la sección [Ejemplos](/ej/ej-caso.qmd) se listan y clasifican las tesis sobresalientes empleadas en esta Guía. Aunque la mayoría de tesis de la facultad de Ciencias Sociales de la PUCP se pueden descargar del {{< fa arrow-up-right-from-square >}} [Repositorio de tesis](https://repositorio.pucp.edu.pe/index/handle/123456789/9120), no existe información pública sobre la calificación que obtuvo cada trabajo.

### Para evaluar tu trabajo con rigurosidad

::: callout-tip
## Estándares

Esta guía presenta, discute e ilustra los criterios de evaluación empleados para calificar una tesis en la facultad.
:::

El [capítulo 2](/caso/02-caso.qmd) presenta los criterios de evaluación de la tesis en la facultad de Ciencias Sociales de la PUCP. Además, discute el significado de estos criterios en el caso de una tesis de este tipo y, por último, ilustra con ejemplos cómo se logra cumplir con el máximo nivel de desempeño en cada criterio.

### Para entender la estructura de una tesis de este tipo

::: callout-tip
## Estructuras

Esta guía discute las estructuras que siguen las tesis de este tipo y sus variedades para que puedas elegir la más apropiada para redactar tu trabajo.
:::

Aunque todos los trabajos deben presentar cierta información, no existe una convención universal sobre la estructura porque el contenedor (la estructura) y el contenido no se pueden escindir y abstraer por completo. Esta guía te proporciona algunos criterios y ejemplos para entender por qué ciertas estructuras funcionan bien para presentar ciertos contenidos. De ese modo, tu puedes tomar tus elecciones.

La [capítulo 2](/caso/02-caso.qmd) presenta los criterios de evaluación de la tesis en la facultad de Ciencias Sociales de la PUCP. Además, discute el significado de estos criterios en el caso de una tesis de este tipo y, por último, ilustra con ejemplos cómo se logra cumplir con el máximo nivel de desempeño en cada criterio.

## ¿Cómo citar esta guía?

Pendiente: Generar DOI para esta guía.

Cornejo, Cesar 2023. Guía de escritura de tesis tipo estudio de caso (no comparativa...

<p class="buttons" style="text-align:center;">

[<i class="bi bi-list-check"></i> Leer esta guía en orden](/caso/01-caso.qmd){.btn .btn-danger} [<i class="bi bi-arrow-up-right-square"></i> Ver ejemplos de este tipo de tesis](/ej/ej-caso.qmd){.btn .btn-danger}

</p>

Algunas tesis sobresalientes con un diseño tipo estudio de caso se pueden
