---
title: "Escribir un ensayo en ciencias sociales"
subtitle: "Guía de escritura de un ensayo académico argumentativo en ciencias sociales"
date-format: DD/MM/YYYY
date: "12/12/2023"

bibliography: references.bib
reference-location: margin

number-sections: true
number-depth: 2
crossref:
  chapters: true

engine: knitr
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

:::: callout-tip
## Ideas centrales
::: justify
1.  En ciencias sociales, los ensayos académicos son un tipo de texto escrito que se utiliza para presentar y defender un argumento o tesis. Un ensayo argumentativo tiene como objetivo persuadir a una audiencia académica de la validez de una afirmación.

2.  Un ensayo académico argumentativo debe defender una **tesis**, que es una afirmación que el autor sostiene que es verdadera. La **tesis** debe ser defendida con razonamientos lógicos (argumentos) y evidencias, y debe estar respaldada por una investigación exhaustiva.

3.  El propósito principal de este tipo de ensayo es persuadir de la validez de una **tesis**. Sin embargo, también puede cumplir otros propósitos como analizar, comparar, clarificar conceptos o compartir reflexiones.

4.  La **tesis** provee una estructura lógica al ensayo y determina la organización del texto. El ensayo se estructura en torno a la tesis central, con secciones y discusiones al servicio de demostrar o corroborar esta proposición.

5.  Se redacta un ensayo argumentativo para defender una tesis central a través de razonamientos y evidencias. La tesis funciona como eje vertebrador del ensayo al cual se subordinan todos los elementos.

6.  La tesis no se sostiene por sí sola, necesita razones y evidencias que la sustenten o fundamenten. Los argumentos son las razones y evidencias que se presentan para respaldar la **tesis**. En conjunto, pretenden demostrar la validez de la afirmación nuclear contenida en la **tesis**.

7.  En síntesis, la **tesis** es una afirmación puntual que se busca demostrar, mientras que los argumentos son los razonamientos lógicos construidos para realizar la demostración.
:::
::::

::: justify
Esta guía te suministra tres insumos indispensables para escribir una tesis sobresaliente: una estructura lógica para escribir tu trabajo, ejemplos analizados de tesis bien escritas y los criterios de calificación que se emplean para evaluar una tesis sobresaliente.

La estructura contiene todos los componentes que necesitas desarrollar cuando escribes una tesis. Los ejemplos te ofrecen análisis de algunas de las mejores tesis recientes sustentadas en la facultad. Los criterios de calificación desagregan la rúbrica oficial de calificación de tesis de la facultad y los emplean para calificar una tesis sobresaliente.
:::

# Propuesta completa {.unnumbered}

::: justify
Un ensayo puede perseguir varios propósitos: analizar, comparar, clarificar, reflexionar, persuadir o argumentar, entre otros. Estos propósitos no son excluyentes; sin embargo, es útil tener en claro el propósito principal del texto que uno va escribir. Esta guía te orientará en la escritura de un ensayo académico argumentativo. En mi propuesta, un ensayo académico argumentativo presenta dos características que lo definen: defiende una **tesis** ---hipótesis, postura o argumento--- y esta escrito para ser evaluado por una audiencia académica delimitada. En este caso, la audiencia es la comunidad de investigadores y profesionales de las ciencias sociales.
:::

## La tesis, la hipótesis, la postura y el argumento {.unnumbered}

::: justify
La **tesis** es la idea central del ensayo, la proposición principal que articula todo el ensayo. Algunos prefieren hablar de hipótesis o argumentos. La **tesis** estructura el ensayo en dos dimensiones: provee una estructura lógica y determina la estructura del texto. Este ensayo estructura en torno a la tesis central, con secciones y discusiones al servicio de esta proposición.

Una **tesis** se formula como una afirmación directa y tajante y sin matices que requiere demostración o defensa. Se escribe un ensayo para defender una **tesis** a través de argumentos y evidencias. La tesis funciona como eje vertebrador del ensayo al cual se subordinan todos los elementos.

En este sentido, algunos prefieren tomar prestado el lenguaje de la ciencia y prefieren presentar una hipótesis. En teoría, la hipótesis es una suposición que se busca demostrar o refutar a través de la investigación y el análisis de datos. Por lo tanto, al plantear una hipótesis el autor debería estar dispuesto a refutar su propio planteamiento, y ello puede resultar en una argumentación débil o poco persuasiva. Por ello, dado que esta propuesta tiene como principal propósito persuadir a una audiencia académica, prefiero el término **tesis** al de hipótesis.

Otros términos empleados en el mismo sentido son postura y argumento. En los textos de argumentación en inglés, se habla de *claim* y se emplea en español como postura. Sin embargo, *claim* se traduce mejor como *afirmación* o *aseveración*. Por ello, mi propuesta prefiere emplear **tesis** como término más equivalente a *claim*, en lugar de postura. Hasta aquí, la única desventaja de emplear **tesis** es su origen en el terreno de lógica y la filosofía más que en el campo de la argumentación contemporánea, que prefiere el término *claim*. Sin embargo, en español, **tesis** comunica mejor el propósito del ensayo argumentativo ---defender una **tesis**--- que postura. En Estudios Generales Letras, los profesores se han decantado por el uso del término postura. Para quienes se hayan instruido con esos materiales, postura es equivalente a lo que denomino **tesis** en esta Guía.

En otros materiales, postura es un término menos delimitado, un indicador de la posición particular que adopta el autor frente a un problema, debate o fenómeno estudiado. Es decir, la postura representa la perspectiva del autor, su ángulo interpretativo o explicativo. Se puede considerar a la postura como el contexto argumentativo que contiene a la **tesis**, el enfoque más amplio.

El argumento está compuesto de las razones las razones o evidencias que se presentan para respaldar la **tesis**. Los argumentos constituyen las partes que en su conjunto pretenden demostrar la afirmación nuclear contenida en la tesis. En las ciencias sociales, diferentes productos académicos se construyen en torno a argumentos. Ello genera confusión en quienes recién se inician en la escritura, porque resulta difícil delimitar un argumento. En cierto sentido, se pueden identificar argumentos a diferentes niveles: el argumento del ensayo, el argumento de una sección, el argumento de un párrafo. Por ejemplo, se podría decir que el texto de esta propuesta tiene tres argumentos: El primer argumento de mi propuesta es que la **tesis** debe ser una afirmación clara y concisa. El segundo argumento es que la **tesis** debe estar respaldada por una investigación exhaustiva. El tercer argumento es que los argumentos deben estar organizados de manera lógica, y organizados en el orden que contribuya mejor a la demostración de la **tesis**.

En síntesis, la **tesis** es una afirmación puntual que se busca demostrar, la postura es la perspectiva personal frente al problema, y los argumentos son los razonamientos articulados para defender la tesis que responde a dicha postura o enfoque interpretativo.
:::

# Estructura, ejemplo, calificación {.unnumbered}

::: justify
Esta guía te suministra tres insumos indispensables para escribir un ensayo en cualquier disciplina de las ciencias sociales: una estructura lógica para escribir tu trabajo, un ejemplo analizado de un ensayo bien escrito y los criterios de calificación que se emplean para evaluar tu ensayo.

La estructura contiene todos las instrucciones para escribir todas las partes del ensayo. El ejemplo te ofrecen análisis de un ensayo reciente calificado con la máxima nota (20) en un curso de la facultad. La rúbrica presenta los criterios de calificación del ensayo.
:::

# Estructura

::: justify
La estructura de un ensayo cumple un papel crucial al sostener, organizar y dar forma a los argumentos que defienden la **tesis**, permitiendo que las ideas se desarrollen de manera clara y efectiva. Todo ensayo tiene una estructura similar: tres partes que cumplen propósitos específicos en el proceso de demostración de la tesis.
:::

::: callout-tip
## Idea central
Las tres partes del ensayo argumentativo son:

- Introducción [Ver capítulo](/ensayo/01-ensayo.qmd)
- Desarrollo [Ver capítulo](/ensayo/02-ensayo.qmd)
- Conclusión [Ver capítulo](/ensayo/03-ensayo.qmd)

Estos tres capítulos te ofrecen instrucciones directas para escribir todas las partes del ensayo con propósitos bien definidos

:::

# Ejemplo

::: callout-tip
## Idea central

[El ejemplo](/ej/cornejo2022.qmd) te ofrece el análisis de un ensayo reciente calificado con la máxima nota (20) en un curso de la facultad.
:::


# Calificación

::: callout-tip
## Idea central

[Este rúbrica](/resource/rubrica-ensayo.qmd) presenta los criterios de evaluación del ensayo argumentativo en ciencias sociales.
:::


## ¿Cómo citar esta guía? {.unnumbered}

Pendiente: Generar DOI para esta guía.

Cornejo, Cesar 2023. Escribir un ensayo en ciencias sociales. Guía de escritura de un ensayo académico argumentativo en ciencias sociales.

<p class="buttons" style="text-align:center;">

[<i class="bi bi-list-check"></i> Leer esta guía en orden](/ensayo/01-ensayo.qmd){.btn .btn-danger} [<i class="bi bi-arrow-up-right-square"></i> Ver los criterios de calificación](/resource/rubrica-ensayo.qmd){.btn .btn-danger}

</p>
