---
title: "Lista de recursos disponibles"
---

# Mejores tesis

Tesis ganadoras del concurso anual de mejores tesis de la Facultad de Ciencias Sociales PUCP

## Antropología

## Ciencia política

## Economía

## Sociología
 &nbsp;
---
| Año del concurso | Tesis | Título | Enfoque metodológico | Tema |
|:-----------------:|:-----:|:------:|:---------------------:|:----:|
| 2023              | Arrunátegui (2020) <br> [Ver este ejemplo](/ej/arrunategui2020.qmd) | Entre el currículo y la memoria: tensiones y negociaciones en la enseñanza de la violencia política por parte de cuatro docentes de un colegio público y emblemático de Lima-Metropolitana | Estudio de caso, teoría fundamentada, perspectiva etnográfica | educación, memoria, historia reciente, docentes, currículo escolar, experiencia, violencia política |
| 2022              | Arrunátegui (2020) <br>  | Entre el currículo y la memoria: tensiones y negociaciones en la enseñanza de la violencia política por parte de cuatro docentes de un colegio público y emblemático de Lima-Metropolitana | Estudio de caso, teoría fundamentada, perspectiva etnográfica | educación, memoria, historia reciente, docentes, currículo escolar, experiencia, violencia política |
| 2021              | Arrunátegui (2020) <br>  | Entre el currículo y la memoria: tensiones y negociaciones en la enseñanza de la violencia política por parte de cuatro docentes de un colegio público y emblemático de Lima-Metropolitana | Estudio de caso, teoría fundamentada, perspectiva etnográfica | educación, memoria, historia reciente, docentes, currículo escolar, experiencia, violencia política |
| 2020              | Arrunátegui (2020) <br> [Ver este ejemplo](/ej/arrunategui2020.qmd) | Entre el currículo y la memoria: tensiones y negociaciones en la enseñanza de la violencia política por parte de cuatro docentes de un colegio público y emblemático de Lima-Metropolitana | Estudio de caso, teoría fundamentada, perspectiva etnográfica | educación, memoria, historia reciente, docentes, currículo escolar, experiencia, violencia política |
 2019              | Arrunátegui (2020) <br> | Entre el currículo y la memoria: tensiones y negociaciones en la enseñanza de la violencia política por parte de cuatro docentes de un colegio público y emblemático de Lima-Metropolitana | Estudio de caso, teoría fundamentada, perspectiva etnográfica | educación, memoria, historia reciente, docentes, currículo escolar, experiencia, violencia política 

: Tesis de sociología ganadores del Concurso Mejores Tesis 2017-2023 {#tbl-mejores-sociología}

# Anuncio de ganadores del Concurso de tesis

: Lista de ganadores del Concurso Mejores Tesis 2017-2023 {#tbl-anuncio-ganadores}

| Año del concurso |
|:-----------------:|
| [2023](https://facultad.pucp.edu.pe/ciencias-sociales/notas-de-prensa/felicitamos-a-los-las-ganadores-as-del-concurso-mejores-tesis-2023/) |
| [2021-2022](https://facultad.pucp.edu.pe/ciencias-sociales/notas-de-prensa/ganadores-concurso-mejores-tesis-2021-2022-de-la-facultad-de-ciencias-sociales/) |
| [2019-2020](https://facultad.pucp.edu.pe/ciencias-sociales/notas-de-prensa/anunciamos-a-los-y-las-ganadoras-del-concurso-extraordinario-de-mejores-tesis-defendidas-entre-1-de-octubre-del-2019-y-el-14-de-junio-del-2020/) |
| [2018](https://facultad.pucp.edu.pe/ciencias-sociales/notas-de-prensa/resultados-concurso-tesis-2018/) |
| [2017](https://facultad.pucp.edu.pe/ciencias-sociales/premiacion/ganadores-tesis-licenciatura/) |

