---
title: "Rúbrica de calificación de tesis"
---

| Criterio                                 | Bien                                                                                                                                                                                                                                      | Muy bien                                                                                                                                                                                                                                                               | Sobresaliente                                                                                                                                                                                                                                                                                                                                             |
|-----------------|-----------------|-----------------|----------------------|
| Planteamiento del problema               | Plantea con claridad el tema de la investigación y justifica su relevancia. Hay coherencia entre las preguntas de investigación y la problemática planteada. Ubica la problemática en diálogo con otros autores, tendencias y/o enfoques. | Plantea con claridad el tema de la investigación y justifica su relevancia. Hay coherencia entre las preguntas de investigación y la problemática planteada. Ubica la problemática en diálogo con otros autores, tendencias y/o enfoques.                             |  Plantea con claridad el tema de la investigación y justifica su relevancia. El tema y enfoque son novedosos, complejos y/o originales. Hay coherencia entre las preguntas de investigación y la problemática planteada. Ubica la problemática en dialogo con otros autores, tendencias y/o enfoques.   [Ver ejemplo](/ej/arrunategui2020.html#calificación){.btn .btn-danger}                                                    |
|                                          |                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                           |
| Referentes teóricos                      | Presenta de manera apropiada los conceptos y/o enfoques teóricos desde la disciplina que orientan su investigación.                                                                                                                       | Presenta de manera apropiada los conceptos y/o enfoques teóricos desde la disciplina que orientan su investigación, construyendo una discusión teórica propia para el abordaje de su problema de investigación.                                                        | Presenta de manera apropiada los conceptos y/o enfoques teóricos desde la disciplina que orientan su investigación, construyendo una discusión teórica propia para el abordaje de su problema de investigación, incorporando elementos novedosos como conceptos de otras disciplinas o estableciendo nuevos usos para conceptos propios de la disciplina.            [Ver ejemplo](/ej/ej-caso.qmd){.btn .btn-primary} |
|                                          |                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                           |
| Datos y métodos                          | Emplea de forma adecuada herramientas y enfoques metodológicos de la disciplina y da cuenta de la forma en que fueron aplicados.                                                                                                          | Emplea de forma adecuada herramientas y enfoques metodológicos de la disciplina y da cuenta de la forma en que fueron aplicados. Presenta reflexiones metodológicas que dan cuenta de la construcción de sus datos.                                                    | Muestra un dominio sólido de las herramientas y enfoques metodológicos utilizados y da cuenta de la forma en que fueron aplicados. Presenta reflexiones metodológicas detalladas que explican la construcción de sus datos.  [Ver ejemplo](/ej/ej-caso.qmd){.btn .btn-primary}                                                                                                                              |
|                                          |                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                           |
| Presentación de hallazgos y conclusiones | Presenta datos suficientes para responder a su pregunta de investigación, organizándolos de manera lógica y en relación con el problema planteado, analizándolos y sacando las conclusiones pertinentes.                                  | Presenta datos suficientes para responder a su pregunta de investigación, organizándolos de manera lógica y en relación con el problema planteado, analizándolos apoyándose en la revisión de la literatura y el marco teórico y sacando las conclusiones pertinentes. | Exhibe riqueza en los datos para responder a su pregunta de investigación, organizándolos de manera lógica y en relación con el problema planteado, analizándolos en diálogo con el marco conceptual y la revisión de literatura, explicitando aportes, como futuras preguntas o líneas de investigación, nueva evidencia, recomendaciones, etc. [Ver ejemplo](/ej/otero2022.html#calificación){.btn .btn-danger}           |
|                                          |                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                           |
| Exposición oral                          | La exposición muestra un orden y estructura comprensibles, respetando el tiempo asignado y respondiendo adecuadamente las preguntas del jurado.                                                                                           | La exposición muestra un orden y estructura comprensibles, apoyándose en organizadores gráficos. Respeta el tiempo asignado y responde adecuadamente las preguntas del jurado.                                                                                         | La exposición muestra un orden y estructura comprensibles, apoyándose en organizadores gráficos que facilitan la comprensión. Respeta el tiempo asignado y responde con solvencia las preguntas del jurado.                                                                                                                                               |

: Rúbrica {#tbl-rubrica}

Fuente: El 2022, la facultad aprobó los ["Criterios de calidad de trabajos conducentes a la obtención de título profesional y asignación de menciones Facultad de Ciencias Sociales 2022"](https://facultad.pucp.edu.pe/ciencias-sociales/wp-content/uploads/2022/07/InformacionEstudiantes-CriteriosCalidadTrabajosConducentesTitulacion-FCCSS.pdf#:~:text=Criterios%20m%C3%ADnimos%20de%20calidad%20para%20trabajos%20conducentes%20a,conclusiones%20y%20bibliograf%C3%ADa%20%28en%20formato%20APA%20m%C3%A1s%20reciente%29.).