---
title: "Arrunátegui 2020"
bibliography: references.bib
reference-location: margin
---

# Datos de la tesis

|                                                                    |                                                                |
|:-------------------------------------------------|:---------------------|
| Tipo de diseño                                                     | estudio de caso                                                |
| Especialidad                                                       | sociología                                                     |
| Área temática                                                      | educación (docentes y currículo escolar) y violencia política  |
| Otros identificadores                                              | memoria, historia reciente, experiencia                        |
| Tesis completa                                                     | Repositorio de tesis PUCP [@arrunátegui2020]                   |
| Publicación académica a partir de la tesis                         | Revista Peruana de Investigación Educativa [@arrunátegui2021]  |
| Video con reflexiones de la autora relacionados a la investigación | {{< video https://youtu.be/7n6-I8eNmLQ?si=j-3k0Jk9i-eZMz5l >}} |
| Autora                                                             | Gabriela Arrunátegui                                           |
| Asesora                                                            | Fanni Muñoz                                                    |

: Arrunátegui 2020. Datos de la tesis. {#tbl-arrunategui2020-datos} {tbl-colwidths="\[40,60\]"}

::: callout-tip
## Objetivo de la tesis

**comprender**[^1] la manera en que cuatro docentes de un colegio público-emblemático de Lima Metropolitana enseñan el periodo de violencia política
:::

[^1]: **comprender** un fenómeno es uno de los objetivos principales de un estudio de caso

# Estructura de la tesis

## Estructura general

La autora eligió organizar su tesis en 5 capítulos. El capítulo 1 construye el problema de investigación que justifica el emprendimiento académico. El capítulo 2 construye el aparato téorico-metodológico que le permitirá investigar el problema. El capítulo 3 sistematiza su investigación sobre el contexto del estudio (el ministerio, el colegio y los profesores). El capítulo 4 analiza la información que ha acopiado durante su investigación. El capítulo 5 presenta sus reflexiones y recomendaciones.

| Cap. 1                                                  | Cap. 2                                                  | Cap. 3                             | Cap. 4   | Cap. 5                                   |
|----------------------------------------|-------------------------------------------|----------------------------------------|------------------------------|----------------------------------------------|
| Tema <br>- Justificación <br>Problema <br>Pregunta <br>- Objetivos <br>- Hipótesis | Marco teórico <br>- Teoría 1 <br>- Teoría 2 <br>- Teoría 3 <br> Metodología <br>- Diseño <br>- Casos <br>- Herramientas <br>- Ética | Contexto de estudio <br>- Contexto 1 <br>- Contexto 2 <br>- Contexto 3 | Análisis  <br>- Tema 1  <br>- Tema 2  <br>- Tema 3  <br>- Tema 4  <br>- Tema 5  | Reflexiones <br>- Hallazgos por pregunta <br> Recomendaciones <br>- Para actores <br>- De investigación |

: Estructura general de la tesis {#tbl-arrunategui2020-estructura}

## Análisis de la tesis por capítulo

### Capítulo 1: El problema de investigación

::: callout-tip
## ¿Qué hizo?

-   Justifica su interés por estudiar el tema
-   Justifica la relevancia del tema para la sociedad y para la sociología
-   Plantea el problema de investigación
-   Presenta su pregunta de investigación, sus objetivos y sus hipótesis
:::

#### ¿Cómo lo hizo?
La autora identifica un tema (la enseñanza de la violencia política en los colegios), describe el proceso personal que suscitó y maduró su interés por el tema y argumenta que este tema es relevante para la la sociedad y la disciplina sociológica. A continuación, procede a construir su problema de investigación: describe los roles de la educación que los sociólogos han identificado; cómo se incorpora la enseñanza de la historia en la región de América Latina durante el siglo XX; identifica el caso peruano de violencia política, lo define y particulariza; describe el rol que se le adjudicó a la educación finalizado el periodo, e identifica actores e hitos legales y normativos; ubica el proceso que estudia en un proceso mayor de disputa por definir el periodo (¿terrorismo?, ¿conflicto armado interno?, ¿violencia política?); presenta una clasificación de las memorias en disputa, realizada por otro autor; emplea esta clasificación (tres memorias) para describir el proceso que está describiendo (la incorporación de la enseñanza de violencia política en los colegios); ilustra el proceso con eventos relevantes en los diferentes momentos políticos y en este punto puede afirmar de forma persuasiva que:

> Por todo lo expuesto anteriormente, se puede inferir que los lineamientos de enseñanza y los contenidos sobre el periodo de violencia política, dados desde el propio sector educación, se enmarcan en un campo de tensiones y negociones [sic], con momentos en los que se intenta introducir una versión objetiva y desde la memoria de la reconciliación (CVR), pero también se lucha porque aparezca la memoria salvadora y la memoria heroica. (15)

De inmediato, nos mueve hacia la dimensión más operativa del mismo proceso: ¿qué se está enseñando en las aulas?, revisa la literatura[^2] existente en el Perú y la presenta en relación con la literatura disponible para otros países de la región de América Latina. Y, con este desplazamiento, nos plantea un enfoque a este nivel operativo: analizar las prácticas docentes al momento de enseñar la violencia política. En este punto, si confiamos en su diagnóstico del estado de la carencia de investigaciones sociológicas al respecto, la pregunta que nos plantea parece impostergable:

::: {.callout-tip icon="false" appearance="simple"}
[Pregunta de investigación general]{.aside}
<big> ¿De qué manera los docentes de Historia y Formación Ciudadana enseñan el periodo de violencia política en un colegio público y emblemático de Lima Metropolitana?
:::

[^2]: revisión de literatura de lo investigado en el Perú con respecto a la pregunta ¿qué se está enseñando en las aulas?

Para cerrar el capítulo, solo necesitó una página y media para enunciar sus preguntas, objetivos e hipótesis. Todo el trabajo analítico y persuasivo para plantear el problema lo realizó en las diez y siete páginas previas.



#### Calificación

Para evaluar el planteamiento de un problema de investigación, la rúbrica de la facultad emplea 4 criterios. Un desempeño bueno o muy bueno requiere cumplir con los criterios 1, 3 y 4. El **criterio 2** distingue a un desempeño sobresaliente: **un desempeño sobresaliente demanda que el tema y el enfoque sean novedosos, complejos o originales**. Una forma de presentar una novedad es escoger un tema inexplorado por la disciplina. Otra forma de lograrlo es encontrar un enfoque novedoso para un tema que ya ha sido explorado. La complejidad ---coherente y disciplinada--- contribuye al planteamiento de un problema de forma novedosa y original. Esa complejidad se puede alcanzar añadiendo ejes de análisis. Por ejemplo, la autora presenta su problema en diálogo con la literatura regional y navega ---sin extraviarse--- la historia, la educación y la sociología: historia del periodo, la educación sobre la memoria reciente y aquello que la disciplina sociológica ha escrito al respecto. Decantar esta travesía en un discurso fluido, coherente y agradable de leer es sobresaliente.

::: {.callout-warning collapse="false" icon="false"}
## <i class="bi bi-binoculars"></i> Aplicación de la rúbrica

| Criterio de calificación                   | Sí cumple/<br>No cumple |
|-----------------------------------------------------|-------------------|
| 1\. Plantea con claridad el tema de la investigación y justifica su relevancia      | Sí cumple           |
| 2\. El tema y enfoque son novedosos, complejos y/o originales                       | Sí cumple           |
| 3\. Hay coherencia entre las preguntas de investigación y la problemática planteada | Sí cumple           |
| 4\. Ubica la problemática en diálogo con otros autores, tendencias y/o enfoques     | Sí cumple           |

: Calificación de la sección *Planteamiento del Problema* {#tbl-arrunategui2020-rubrica1}


Ver la [rúbrica de calificación](/resource/rubrica.qmd#tbl-rubrica) que orienta la deliberación del jurado en la evaluación de cualquier tesis
:::

### Capítulo 2: Marco teórico y metodología

La autora eligió presentar en un mismo capítulo su marco teórico y su metodología. Aunque el nombre de la sección es preciso, en tanto contiene el *marco teórico* **y** la *metodología*, cada sección es independiente y no hay un diálogo explícito entre ambos componentes de la tesis en esta sección. Por lo tanto, para fines didácticos es más razonable analizarlas por separado. La autora nos refiere al Anexo 1 para observar cómo dialogan estos componentes en su trabajo.

### Capítulo 2.1 Marco teórico

::: callout-tip
## ¿Qué hizo?

Presenta tres enfoques teóricos para analizar el problema planteado:

-   Sociología de la experiencia escolar
-   Memoria e historia en la enseñanza de la historia reciente
-   Desempeño profesional docente en el aula
:::

#### ¿Cómo lo hizo?

Cada enfoque tiene particularidades que demanda una presentación distinta, pero en general, se puede reconocer la siguiente secuencia:

1. Presenta (resume) el enfoque.
2. Presenta la utilidad del enfoque para abordar el problema de investigación.
3. Presenta los conceptos que emplea el enfoque y se considera relevantes para abordar el problema de investigación.
4. Presenta una síntesis de los hallazgos de las investigaciones que han empleado el enfoque en otros países de la región de América Latina
5. Aterriza la discusión del enfoque a la literatura o el análisis del **caso peruano**.
    ii) Cuando hay investigaciones que abordan el asunto, las presenta.
    ii) Cuando el asunto amerita un análisis del **caso peruano**, lo realiza.[^3]

[^3]: En este punto del manuscrito, todavía no ha presentado el caso de estudio. Por lo tanto, hay que distinguir el análisis preliminar que realiza del contexto o situación peruana ---que llama **caso peruano**--- del análisis del caso de estudio que constituye el aporte de esta tesis y que se realizará en una sección posterior.

### Capítulo 2.2 Metodología

::: callout-tip
## ¿Qué hizo?

-   Presenta el diseño metodológico
-   Presenta los casos
-   Presenta las herramientas de recojo de información
-   Presenta los parámetros éticos que guiaron la investigación
:::

#### ¿Cómo lo hizo?

::: callout-tip
## ¿Qué autores guiaron su sección metodológica?

| Fuente                              | Uso                                                                     |
|-------------------------------------|-------------------------------------------------------------------------|
| Gibbs (2012)                 | Definir el propósito de una investigación cualitativa                 |
| Corbin y Strauss (2008)             | Asumir el enfoque de la teoría fundamentada (planteado por los autores)|
| Horst y Karl (2001)                  | Comunicar las posibilidades y los objetivos de un estudio de caso      |
| Hernández (2000)                    | Explicar las posibilidades que ofrece la técnica de la observación     |
| Thompson (1993)                     | Asumir el enfoque biográfico en sus entrevistas a profundidad         |
| Stake (1998); Aguilar y Barroso (2015) | Comunicar las ventajas de usar la triangulación intra-método como procedimiento de análisis |

: Fuentes empleadas en la sección *Metodología* {#tbl-arrunategui2020-fuentes-metodo}

:::

#### Diseño metodológico

::: callout-tip
## ¿Qué hizo?
Lo más importante: justifica su elección metodológica

> Esta tesis optó por trabajar un estudio de caso, el cual posibilita el análisis de personas concretas o unidades sociales observables (como la escuela o la clase escolar) dentro de un periodo de tiempo rigurosamente definido (Horst y Karl, 2001). Este análisis no pretende la generalización o interpretación de otros casos, lo que busca es la comprensión total del caso o casos elegidos. En esa línea, se ha considerado pertinente seleccionar como los casos a cuatro docentes que hayan vivido durante los años de la violencia política (1980-2000) y que enseñen este periodo en los cursos y grados correspondientes. De este modo, se podrá conocer exhaustivamente su práctica pedagógica y lo que sucede con el tratamiento de este tema en la escuela pública donde trabajan^28^. (41)

:::

#### Los casos

::: callout-tip
## ¿Qué hizo?
-   Presenta sus criterios para la selección de los casos (docentes)
-   Presenta los datos generales de cada caso (docente) seleccionado
-   Justifica la elección del colegio (de donde seleccionará los docentes)
    - Presenta características pertinentes del colegio
    - Presenta mapa del colegio
-   Comunica que anonimizó los docentes y el colegio

En base a estos requisitos fue que se seleccionó a los docentes del colegio público-emblemático “San Martín” del distrito del Rímac de Lima Metropolitana.
:::

#### Herramientas de recojo de información

::: callout-tip
## ¿Qué hizo?
-   Presenta las tres herramientas que utilizó
-   Presenta alguna fuente que le permite explicar la utilidad o pertinencia de cada herramienta
-   Describe en detalle cómo se aplicó cada herramienta
-   Presenta cuadros que organizan la información relevante para presentar la herramienta, sus aplicación y los sujetos u objetos de análisis
:::

##### Herramienta 1
##### Técnica: Observación 
-   Observación con perspectiva etnográfica
    -   Observación participante en espacio 1
    -   Observación no participante en espacio 2
-   Justificación de la pertinencia del uso de esta perspectiva y técnica
-   Espacios donde se aplicó
    - Espacio 1: descripción del espacio, tipo de técnica (observación participante): justificación y propósito, medio de registro de información (notas de campo), número de horas y periodo durante el cual se realizó la observación
    - Espacio 2: descripción del espacio, tipo de técnica (observación participante): justificación y propósito, medio de registro de información (notas de campo) y cuadros con el detalle de las fechas, aulas, tiempos y otros detalles relevantes específicos a esta observación

##### Herramienta 2: Entrevistas
-   Entrevistas a cuatro docentes (casos)
      - Tipo: entrevistas a profundidad con enfoque biográfico
      - Justificación: <br>
“permite analizar las trayectorias de vida de los docentes en su desempeño profesional durante el periodo de violencia política y el actual” (47)
     - Detalles: Duración de entrevista y momento en que se realizaron
-   Entrevistas a tres autoridades escolares del colegio
      - Tipo: entrevistas semiestructuradas
      - Justificación: “con el objetivo de conocer los documentos institucionales del colegio y sus opiniones sobre el desempeño de los docentes a su cargo al enseñar el periodo de violencia política.” (47)
      - Detalles: Duración de entrevista y momento en que se realizaron
      - Cuadro con la información sobre las entrevistas realizadas

##### Herramienta 3
-   Revisión documental
    - Cuadro con la lista de los documentos analizados clasificados por la autora en documentos oficiales y documentos personales

##### Destaca el uso de un procedimiento de análisis
-   Triangulación
    -   Justificación
    -   Elementos a triangular: entrevistas, observación y análisis de documentos

#### Ética en la investigación

Remite a los artículos del Reglamento del Comité de Ética para la Investigación con Seres Humanos y Animales de la Pontificia Universidad Católica del Perú (2011) que guiaron su investigación. 

### Capítulo 3: Contextualización del tema

::: callout-tip
## ¿Qué hizo?

Contextualiza el tema ---la enseñanza de la violencia política en la historia, las instituciones y la geografía---

-   Según el MINEDU
-   Según el colegio
-   Según los cuatro docentes (casos)
:::

#### ¿Qué hizo, por qué y para qué?

> El objetivo de este capítulo es contextualizar las decisiones tomadas desde el MINEDU, la IE “San Martín” y sus docentes respecto a la enseñanza del periodo de violencia política. Para ello, se analizarán los documentos institucionales del MINEDU y la IE “San Martín”. Así mismo, conoceremos quiénes son estos cuatro docentes, cuáles son sus opiniones sobre la enseñanza de este tema y sus conocimientos sobre las herramientas curriculares y pedagógicas. (51)

### Capítulo 4: Análisis

::: callout-tip
## ¿Qué hizo?
Analiza las sesiones de clase que observó
:::

#### ¿Cuáles fueron los objetivos de su análisis?
> Los objetivos son (1) analizar su desempeño profesional a través del uso y manejo de los materiales educativos, así como del desarrollo de las competencias y capacidades que cada área curricular busca transmitir a los estudiantes en el aprendizaje de este tema, (2) conocer si incorporan los contenidos de los libros de texto oficiales o son otras las narrativas que comparten en el aula y (3) analizar si estas narrativas guardan alguna relación con las memorias sociales en pugna en el espacio público. (84)

#### ¿Cómo organizó su análisis?
> El análisis se dará en función a los temas más controversiales que atraviesan el periodo de violencia política: (1) su introducción en las aulas, (2) la manera de nombrarlo, (3) las causas, (4) los actores más mencionados: los grupos subversivos, las Fuerzas Armadas y los gobiernos presidenciales de turno, y (5) la Comisión de la Verdad y Reconciliación y su Informe Final. (84)

#### ¿Qué le permite organizar el análisis en función de estos temas?
> A través de ellos podremos conocer qué herramientas curriculares y pedagógicas (oficiales y no oficiales) emplean y cómo se apropian de ellas; así como los relatos del pasado reciente que se transmiten en el aula y su relación con las memorias públicas. También permitirán explorar las relaciones entre las biografías de los y las docentes y el abordaje de este pasado reciente. (84)

A continuación, divide el capítulo en cinco subcapítulos. Cada subcapítulo corresponde a uno de los temas elegidos para organizar su análisis:

- 4.1 La introducción del periodo en el aula
- 4.2 Las heterogéneas y contradictorias formas de nombrar al periodo
- 4.3 Las causas del periodo
- 4.4 Los actores más importantes del periodo
- 4.5 La enseñanza sobre la CVR y su Informe Final

### Capítulo 5: Reflexiones finales y recomendaciones

#### Capítulo 5.1 Reflexiones finales

::: callout-tip
## ¿Qué hizo?
-   Recuerda al lector sus preguntas de investigación (una general y dos específicas) y sus hipótesis
-   Presenta sus hallazgos organizados con respecto a las tres preguntas de investigación que intentó responder
:::

##### ¿Cómo lo hizo?

En esta sección presentó sus hallazgos y los utilizó para responder a las preguntas de investigación que del trabajo. Como el trabajo tiene una pregunta de investigación general y dos preguntas específicas, organizó esta sección con respecto a los temas de cada pregunta de investigación,

[Pregunta de investigación general: ¿De qué manera los docentes de Historia y Formación Ciudadana **enseñan** el periodo de **violencia política** en un colegio público y emblemático de Lima Metropolitana?]{.aside}

1.   Con respecto a la **enseñanza de la violencia política** <br>
      Presenta sus hallazgos y los discute con la literatura (de Perú y de otros países), y con la teoría sociológica

[Pregunta específica 1: ¿Cuál es el **desempeño profesional** que guía al docente de Historia y Formación Ciudadana en el proceso de enseñanza del periodo de violencia política?]{.aside}

2.    Con respecto al **desempeño profesional** de los docentes <br>
      Sintetiza sus observaciones de campo y describe los retos pedagógicos que ha identificado
      
[Pregunta específica 2: ¿¿Cuáles los **relatos sobre el periodo de violencia política** que los docentes de Formación Ciudadana e Historia transmiten en sus clases?]{.aside}

3.    Con respecto a los **relatos sobre el periodo de violencia política** en el aula <br>
      Presenta los resultados que encuentra: describe los relatos que identifica, los actores, la opinión de los docentes y la relación de estos relatos con el contenido de los libros


#### Capítulo 5.1 Recomendaciones

::: callout-tip
## ¿Qué hizo?
De manera breve, en dos páginas:

-   Presenta sus recomendaciones organizadas según a quién las dirige: 
    -   Recomendaciones dirigidas al MINEDU
    -   Recomendaciones dirigidas a la comunidad educativa
-   Presenta recomendaciones de investigación
:::

## Anexos importantes

Presenta los siguientes formatos que son frecuentes en las tesis tipo estudio de caso. Se puede revisar la tesis completa para revisar estos formatos.

### Etapas de la investigación

En este anexo, la autora relata los diversos acercamientos que ha tenido la investigación. Emplea un tono personal para comunicar al lector los procesos que culminaron en la realización de este trabajo, los tiempos de cada etapa durante diferentes cursos, sus acercamientos al campo y las personas que marcaron su recorrido. Esta sección permite entender varias de las elecciones que realiza la investigadora. En la sección de diseño metodológico había adelantado, en un pie de página, algunos de los elementos que nos relata con honestidad y transparencia en este anexo: 

> Es importante dar a conocer que inicialmente en este estudio se planteó trabajar con los docentes de dos colegios públicos y emblemáticos, uno en Ayacucho y otro en Lima. Sin embargo, se decidió finalmente trabajar sólo con el colegio de Lima por dos motivos: (1) profundizar en la investigación con los docentes de Lima y (2) porque las clases en el colegio de Ayacucho se retrasaron por la huelga magisterial peruana que se dio entre julio y septiembre del 2017. (41)

### Otros anexos importantes:

-   Tabla de Operacionalización <br>
    Presenta:
    -   Problema de investigación
    -   Preguntas
    -   Objetivos
    -   Hipótesis
    -   Concepto y/o categoría clave
    -   Variables 
    -   Categorías 
    -   Herramientas metodológicas

-   Guía de observación en el aula

-   Guía de entrevista

## Referencias


